const iphones = [
  {
    productName: "iPhone 12",
    id: "iphone12",
    posterImg: {
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone12-digitalmat-gallery-2-202111?wid=728&hei=666&fmt=png-alpha&.v=1635178709000",
      alt: "Visão da parte da frente e de trás mostrando a tela Super Retina XDR de 6,1 polegadas e a câmera.",
    },
    images: [
      {
        index: 0,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone12-digitalmat-gallery-1-202111?wid=728&hei=666&fmt=png-alpha&.v=1635980933000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635980933000",
          },
          attrs: "",
          alt: "Várias imagens frontais do iPhone 12.",
          width: "364",
          height: "333",
          imageName: "iphone12-digitalmat-gallery-1-202111",
          originalImageName: "iphone12-digitalmat-gallery-1-202111",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: true,
        position: 1,
        first: true,
      },
      {
        index: 1,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone12-digitalmat-gallery-2-202111?wid=728&hei=666&fmt=png-alpha&.v=1635178709000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635178709000",
          },
          attrs: "",
          alt: "Visão da parte da frente e de trás mostrando a tela Super Retina XDR de 6,1 polegadas e a câmera.",
          width: "364",
          height: "333",
          imageName: "iphone12-digitalmat-gallery-2-202111",
          originalImageName: "iphone12-digitalmat-gallery-2-202111",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: false,
        position: 2,
        first: false,
      },
      {
        index: 2,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone12-digitalmat-gallery-3-202111?wid=728&hei=666&fmt=png-alpha&.v=1636673254000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1636673254000",
          },
          attrs: "",
          alt: "Uma mão segura o iPhone 12 para dar uma noção do tamanho.",
          width: "364",
          height: "333",
          imageName: "iphone12-digitalmat-gallery-3-202111",
          originalImageName: "iphone12-digitalmat-gallery-3-202111",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: true,
        position: 3,
        first: false,
      },
      {
        index: 3,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone12-digitalmat-gallery-4-202111?wid=728&hei=666&fmt=png-alpha&.v=1635178709000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635178709000",
          },
          attrs: "",
          alt: "Close do sistema avançado de câmera dupla com as câmeras grande-angular e ultra-angular.",
          width: "364",
          height: "333",
          imageName: "iphone12-digitalmat-gallery-4-202111",
          originalImageName: "iphone12-digitalmat-gallery-4-202111",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: false,
        position: 4,
        first: false,
      },
      {
        index: 4,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone12-digitalmat-gallery-5-202111?wid=728&hei=666&fmt=png-alpha&.v=1635178710000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635178710000",
          },
          attrs: "",
          alt: "Visão lateral mostrando a borda plana, o botão lateral e uma imagem de perfil da câmera.",
          width: "364",
          height: "333",
          imageName: "iphone12-digitalmat-gallery-5-202111",
          originalImageName: "iphone12-digitalmat-gallery-5-202111",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: true,
        position: 5,
        first: false,
      },
      {
        index: 5,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone12-digitalmat-gallery-6-202111?wid=728&hei=666&fmt=png-alpha&.v=1635178710000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635178710000",
          },
          attrs: "",
          alt: "Visão da parte de trás do iPhone 12 com capa de couro e carteira de couro com MagSafe.",
          width: "364",
          height: "333",
          imageName: "iphone12-digitalmat-gallery-6-202111",
          originalImageName: "iphone12-digitalmat-gallery-6-202111",
          noImage: false,
          deferSrc: false,
        },
        last: true,
        even: false,
        position: 6,
        first: false,
      },
    ],
    price: "5699.00",
  },
  {
    productName: "iPhone SE",
    id: "iphonese",
    posterImg: {
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphonese-digitalmat-gallery-3-202203?wid=728&hei=666&fmt=png-alpha&.v=1644987579761",
      alt: "Uma mão segura o iPhone SE para dar uma noção do tamanho.",
    },
    images: [
      {
        index: 0,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphonese-digitalmat-gallery-1-202203?wid=728&hei=666&fmt=png-alpha&.v=1644987579596",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1644987579596",
          },
          attrs: "",
          alt: "Visão angulada das três cores do iPhone SE, incluindo (PRODUCT)RED, estelar e meia-noite, além de uma visão angulada da parte da frente na cor meia-noite.",
          width: "364",
          height: "333",
          imageName: "iphonese-digitalmat-gallery-1-202203",
          originalImageName: "iphonese-digitalmat-gallery-1-202203",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: true,
        position: 1,
        first: true,
      },
      {
        index: 1,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphonese-digitalmat-gallery-2-202203?wid=728&hei=666&fmt=jpeg&qlt=90&.v=1646075827246",
            scaleParams1: "wid=364&hei=333&fmt=jpeg&qlt=95&.v=1646075827246",
          },
          attrs: "",
          alt: "Uma mão segura o iPhone SE para dar uma noção do tamanho.",
          width: "364",
          height: "333",
          imageName: "iphonese-digitalmat-gallery-2-202203",
          originalImageName: "iphonese-digitalmat-gallery-2-202203",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: false,
        position: 2,
        first: false,
      },
      {
        index: 2,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphonese-digitalmat-gallery-3-202203?wid=728&hei=666&fmt=png-alpha&.v=1644987579761",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1644987579761",
          },
          attrs: "",
          alt: "Visão da parte da frente e de trás mostrando a tela Retina de 4,7 polegadas e a câmera.",
          width: "364",
          height: "333",
          imageName: "iphonese-digitalmat-gallery-3-202203",
          originalImageName: "iphonese-digitalmat-gallery-3-202203",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: true,
        position: 3,
        first: false,
      },
      {
        index: 3,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphonese-digitalmat-gallery-4-202203?wid=728&hei=666&fmt=png-alpha&.v=1644987579760",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1644987579760",
          },
          attrs: "",
          alt: "Close da câmera.",
          width: "364",
          height: "333",
          imageName: "iphonese-digitalmat-gallery-4-202203",
          originalImageName: "iphonese-digitalmat-gallery-4-202203",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: false,
        position: 4,
        first: false,
      },
      {
        index: 4,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphonese-digitalmat-gallery-5-202203?wid=728&hei=666&fmt=png-alpha&.v=1644987579701",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1644987579701",
          },
          attrs: "",
          alt: "Visão lateral mostrando a borda arredondada, o botão lateral e uma imagem de perfil da câmera.",
          width: "364",
          height: "333",
          imageName: "iphonese-digitalmat-gallery-5-202203",
          originalImageName: "iphonese-digitalmat-gallery-5-202203",
          noImage: false,
          deferSrc: false,
        },
        last: true,
        even: true,
        position: 5,
        first: false,
      },
    ],
    price: "4299.00",
  },
  {
    productName: "iPhone 14",
    id: "iphone14",
    posterImg: {
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14-digitalmat-gallery-3-202209?wid=728&hei=666&fmt=png-alpha&.v=1662055813794",
      alt: "Uma mão segura o iPhone 14 para dar uma noção do tamanho.",
    },
    images: [
      {
        index: 0,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14-digitalmat-gallery-1-202209?wid=728&hei=666&fmt=png-alpha&.v=1662055813734",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1662055813734",
          },
          attrs: "",
          alt: "Imagem angulada das cinco cores do iPhone 14, incluindo meia-noite, roxo, estelar, (PRODUCT)RED e azul, e imagem angulada da parte da frente em azul.",
          width: "364",
          height: "333",
          imageName: "iphone14-digitalmat-gallery-1-202209",
          originalImageName: "iphone14-digitalmat-gallery-1-202209",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: true,
        position: 1,
        first: true,
      },
      {
        index: 1,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14-digitalmat-gallery-2-202209?wid=728&hei=666&fmt=png-alpha&.v=1662055814304",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1662055814304",
          },
          attrs: "",
          alt: "Uma mão segura o iPhone 14 para dar uma noção do tamanho.",
          width: "364",
          height: "333",
          imageName: "iphone14-digitalmat-gallery-2-202209",
          originalImageName: "iphone14-digitalmat-gallery-2-202209",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: false,
        position: 2,
        first: false,
      },
      {
        index: 2,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14-digitalmat-gallery-3-202209?wid=728&hei=666&fmt=png-alpha&.v=1662055813794",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1662055813794",
          },
          attrs: "",
          alt: "Imagem da parte da frente e de trás mostrando a tela Super Retina XDR de 6,1 polegadas e o sistema avançado de câmera dupla com lentes posicionadas na diagonal.",
          width: "364",
          height: "333",
          imageName: "iphone14-digitalmat-gallery-3-202209",
          originalImageName: "iphone14-digitalmat-gallery-3-202209",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: true,
        position: 3,
        first: false,
      },
      {
        index: 3,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14-digitalmat-gallery-4-202209?wid=728&hei=666&fmt=jpeg&qlt=90&.v=1662055813751",
            scaleParams1: "wid=364&hei=333&fmt=jpeg&qlt=95&.v=1662055813751",
          },
          attrs: "",
          alt: "Close do sistema avançado de câmera dupla com as câmeras grande-angular e ultra-angular.",
          width: "364",
          height: "333",
          imageName: "iphone14-digitalmat-gallery-4-202209",
          originalImageName: "iphone14-digitalmat-gallery-4-202209",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: false,
        position: 4,
        first: false,
      },
      {
        index: 4,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14-digitalmat-gallery-5-202209?wid=728&hei=666&fmt=png-alpha&.v=1662055808737",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1662055808737",
          },
          attrs: "",
          alt: "Imagem lateral mostrando a borda plana, o botão lateral e um perfil do sistema de câmera dupla.",
          width: "364",
          height: "333",
          imageName: "iphone14-digitalmat-gallery-5-202209",
          originalImageName: "iphone14-digitalmat-gallery-5-202209",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: true,
        position: 5,
        first: false,
      },
      {
        index: 5,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14-digitalmat-gallery-6-202209?wid=728&hei=666&fmt=png-alpha&.v=1662055814083",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1662055814083",
          },
          attrs: "",
          alt: "Imagem da parte de trás de três smartphones iPhone 14. Todos eles têm vários acessórios MagSafe. O primeiro tem uma capa e uma carteira magnética MagSafe. O segundo tem uma capa e um carregador magnético. O terceiro tem uma capa e uma bateria externa magnética. Cores contrastantes mostram a diversão de combinar e recombinar os acessórios MagSafe. ",
          width: "364",
          height: "333",
          imageName: "iphone14-digitalmat-gallery-6-202209",
          originalImageName: "iphone14-digitalmat-gallery-6-202209",
          noImage: false,
          deferSrc: false,
        },
        last: true,
        even: false,
        position: 6,
        first: false,
      },
    ],
    price: "7599.00",
  },
  {
    productName: "iPhone 14 Pro",
    id: "iphone14pro",
    posterImg: {
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14pro-digitalmat-gallery-5-202209?wid=728&hei=666&fmt=png-alpha&.v=1663346233360",
      alt: "Uma mão segura o iPhone 14 Pro para dar uma noção do tamanho.",
    },
    images: [
      {
        index: 0,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14pro-digitalmat-gallery-1-202209?wid=728&hei=666&fmt=png-alpha&.v=1660830514655",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1660830514655",
          },
          attrs: "",
          alt: "Imagem angulada das quatro cores do iPhone 14 Pro, incluindo preto-espacial, prateado, dourado e roxo-profundo, e imagem angulada da parte da frente em roxo-profundo.\n",
          width: "364",
          height: "333",
          imageName: "iphone14pro-digitalmat-gallery-1-202209",
          originalImageName: "iphone14pro-digitalmat-gallery-1-202209",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: true,
        position: 1,
        first: true,
      },
      {
        index: 1,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14pro-digitalmat-gallery-2-202209?wid=728&hei=666&fmt=png-alpha&.v=1660830896841",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1660830896841",
          },
          attrs: "",
          alt: "Uma mão segura o iPhone 14 Pro para dar uma noção do tamanho.",
          width: "364",
          height: "333",
          imageName: "iphone14pro-digitalmat-gallery-2-202209",
          originalImageName: "iphone14pro-digitalmat-gallery-2-202209",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: false,
        position: 2,
        first: false,
      },
      {
        index: 2,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14pro-digitalmat-gallery-3-202209_GEO_BR?wid=728&hei=666&fmt=png-alpha&.v=1664838364100",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1664838364100",
          },
          attrs: "",
          alt: "A imagem mostra a parte da frente de três smartphones iPhone 14 Pro Max sobrepostos. A nova Dynamic Island, que exibe notificações, alertas e atividades ao vivo, aparece em três formatos diferentes. O primeiro mostra apenas a nova câmera frontal na Dynamic Island. O segundo mostra como o hardware se expande em uma notificação de software indicando que os AirPods estão conectados. The third shows how Dynamic Island morphs into controls for music.   ",
          width: "364",
          height: "333",
          imageName: "iphone14pro-digitalmat-gallery-3-202209_GEO_BR",
          originalImageName: "iphone14pro-digitalmat-gallery-3-202209_GEO_BR",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: true,
        position: 3,
        first: false,
      },
      {
        index: 3,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14pro-digitalmat-gallery-4-202209?wid=728&hei=666&fmt=jpeg&qlt=90&.v=1660830896885",
            scaleParams1: "wid=364&hei=333&fmt=jpeg&qlt=95&.v=1660830896885",
          },
          attrs: "",
          alt: "Close do sistema de câmera Pro com as câmeras teleobjetiva, grande-angular e ultra-angular.",
          width: "364",
          height: "333",
          imageName: "iphone14pro-digitalmat-gallery-4-202209",
          originalImageName: "iphone14pro-digitalmat-gallery-4-202209",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: false,
        position: 4,
        first: false,
      },
      {
        index: 4,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14pro-digitalmat-gallery-5-202209?wid=728&hei=666&fmt=png-alpha&.v=1663346233360",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1663346233360",
          },
          attrs: "",
          alt: "Imagem da parte da frente e de trás mostrando a tela Super Retina XDR de 6,1 polegadas e o sistema de câmera Pro.",
          width: "364",
          height: "333",
          imageName: "iphone14pro-digitalmat-gallery-5-202209",
          originalImageName: "iphone14pro-digitalmat-gallery-5-202209",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: true,
        position: 5,
        first: false,
      },
      {
        index: 5,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14pro-digitalmat-gallery-6-202209?wid=728&hei=666&fmt=png-alpha&.v=1660830896167",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1660830896167",
          },
          attrs: "",
          alt: "Imagem lateral mostrando a borda plana, o botão lateral e um perfil do sistema de câmera Pro.",
          width: "364",
          height: "333",
          imageName: "iphone14pro-digitalmat-gallery-6-202209",
          originalImageName: "iphone14pro-digitalmat-gallery-6-202209",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: false,
        position: 6,
        first: false,
      },
      {
        index: 6,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone14pro-digitalmat-gallery-7-202209?wid=728&hei=666&fmt=png-alpha&.v=1661443551002",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1661443551002",
          },
          attrs: "",
          alt: "Imagem da parte de trás de três smartphones iPhone 14 Pro. Todos eles têm vários acessórios MagSafe. O primeiro tem uma capa e uma carteira magnética MagSafe. O segundo tem uma capa e um carregador magnético. O terceiro tem uma capa e uma bateria externa magnética. Cores contrastantes mostram a diversão de combinar e recombinar os acessórios MagSafe. ",
          width: "364",
          height: "333",
          imageName: "iphone14pro-digitalmat-gallery-7-202209",
          originalImageName: "iphone14pro-digitalmat-gallery-7-202209",
          noImage: false,
          deferSrc: false,
        },
        last: true,
        even: true,
        position: 7,
        first: false,
      },
    ],
    price: "9499.00",
  },
  {
    productName: "iPhone 13",
    id: "iphone13",
    posterImg: {
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone13-digitalmat-gallery-3-202203?wid=728&hei=666&fmt=png-alpha&.v=1644988765122",
      alt: "Uma mão segura o iPhone 13 para dar uma noção do tamanho.",
    },
    images: [
      {
        index: 0,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone13-digitalmat-gallery-1-202203?wid=728&hei=666&fmt=png-alpha&.v=1645574660282",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1645574660282",
          },
          attrs: "",
          alt: "Visão angulada das seis cores do iPhone 13, incluindo (PRODUCT)RED, estelar, meia-noite, azul, rosa e verde, e visão angulada da parte da frente em verde.",
          width: "364",
          height: "333",
          imageName: "iphone13-digitalmat-gallery-1-202203",
          originalImageName: "iphone13-digitalmat-gallery-1-202203",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: true,
        position: 1,
        first: true,
      },
      {
        index: 1,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone13-digitalmat-gallery-2-202203?wid=728&hei=666&fmt=png-alpha&.v=1644988764167",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1644988764167",
          },
          attrs: "",
          alt: "Uma mão segura o iPhone 13 para dar uma noção do tamanho.",
          width: "364",
          height: "333",
          imageName: "iphone13-digitalmat-gallery-2-202203",
          originalImageName: "iphone13-digitalmat-gallery-2-202203",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: false,
        position: 2,
        first: false,
      },
      {
        index: 2,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone13-digitalmat-gallery-3-202203?wid=728&hei=666&fmt=png-alpha&.v=1644988765122",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1644988765122",
          },
          attrs: "",
          alt: "Visão da parte da frente e de trás mostrando a tela Super Retina XDR de 6,1 polegadas e o sistema avançado de câmera dupla com lentes posicionadas na diagonal.",
          width: "364",
          height: "333",
          imageName: "iphone13-digitalmat-gallery-3-202203",
          originalImageName: "iphone13-digitalmat-gallery-3-202203",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: true,
        position: 3,
        first: false,
      },
      {
        index: 3,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone13-digitalmat-gallery-4-202203?wid=728&hei=666&fmt=jpeg&qlt=90&.v=1644988764203",
            scaleParams1: "wid=364&hei=333&fmt=jpeg&qlt=95&.v=1644988764203",
          },
          attrs: "",
          alt: "Close do sistema avançado de câmera dupla com as câmeras grande-angular e ultra-angular.",
          width: "364",
          height: "333",
          imageName: "iphone13-digitalmat-gallery-4-202203",
          originalImageName: "iphone13-digitalmat-gallery-4-202203",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: false,
        position: 4,
        first: false,
      },
      {
        index: 4,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone13-digitalmat-gallery-5-202203?wid=728&hei=666&fmt=png-alpha&.v=1644988764132",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1644988764132",
          },
          attrs: "",
          alt: "Visão lateral mostrando a borda plana, o botão lateral e uma imagem de perfil do sistema de câmera dupla.",
          width: "364",
          height: "333",
          imageName: "iphone13-digitalmat-gallery-5-202203",
          originalImageName: "iphone13-digitalmat-gallery-5-202203",
          noImage: false,
          deferSrc: false,
        },
        last: false,
        even: true,
        position: 5,
        first: false,
      },
      {
        index: 5,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone13-digitalmat-gallery-6-202203?wid=728&hei=666&fmt=png-alpha&.v=1644988764137",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1644988764137",
          },
          attrs: "",
          alt: "Visão da parte de trás do iPhone 13 com capa de silicone com MagSafe.",
          width: "364",
          height: "333",
          imageName: "iphone13-digitalmat-gallery-6-202203",
          originalImageName: "iphone13-digitalmat-gallery-6-202203",
          noImage: false,
          deferSrc: false,
        },
        last: true,
        even: false,
        position: 6,
        first: false,
      },
    ],
    price: "6499.00",
  },
];
const mac = [
  {
    productName: "MacBook Air com M1",
    id: "imacairm1",
    posterImg: {
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba-digitalmat-gallery-2-202111?wid=728&hei=666&fmt=png-alpha&.v=1636156358000",
      alt: "Visão frontal da tela Retina de alto contraste.",
    },
    images: [
      {
        index: 0,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba-digitalmat-gallery-1-202111?wid=728&hei=666&fmt=png-alpha&.v=1636156517000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1636156517000",
          },
          attrs: "",
          alt: "Visão superior de modelos do MacBook Air em três cores: dourado, prateado e cinza-espacial.",
          width: "364",
          height: "333",
          imageName: "mba-digitalmat-gallery-1-202111",
          originalImageName: "mba-digitalmat-gallery-1-202111",
          noImage: false,
          deferSrc: false,
        },
        first: true,
        position: 1,
        even: true,
        last: false,
      },
      {
        index: 1,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba-digitalmat-gallery-2-202111?wid=728&hei=666&fmt=png-alpha&.v=1636156358000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1636156358000",
          },
          attrs: "",
          alt: "Visão frontal da tela Retina de alto contraste.",
          width: "364",
          height: "333",
          imageName: "mba-digitalmat-gallery-2-202111",
          originalImageName: "mba-digitalmat-gallery-2-202111",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 2,
        even: false,
        last: false,
      },
      {
        index: 2,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba-digitalmat-gallery-3-202111?wid=728&hei=666&fmt=png-alpha&.v=1635187293000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635187293000",
          },
          attrs: "",
          alt: "Visão lateral das duas portas Thunderbolt do lado esquerdo.",
          width: "364",
          height: "333",
          imageName: "mba-digitalmat-gallery-3-202111",
          originalImageName: "mba-digitalmat-gallery-3-202111",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 3,
        even: true,
        last: false,
      },
      {
        index: 3,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba-digitalmat-gallery-4-202111_GEO_BR?wid=728&hei=666&fmt=png-alpha&.v=1636244985000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1636244985000",
          },
          attrs: "",
          alt: "Visão aérea do teclado com trackpad integrado.",
          width: "364",
          height: "333",
          imageName: "mba-digitalmat-gallery-4-202111_GEO_BR",
          originalImageName: "mba-digitalmat-gallery-4-202111_GEO_BR",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 4,
        even: false,
        last: false,
      },
      {
        index: 4,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mba-digitalmat-gallery-5-202111?wid=728&hei=666&fmt=png-alpha&.v=1635187292000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635187292000",
          },
          attrs: "",
          alt: "Visão superior do MacBook Air prateado fechado com o logotipo da Apple no centro.",
          width: "364",
          height: "333",
          imageName: "mba-digitalmat-gallery-5-202111",
          originalImageName: "mba-digitalmat-gallery-5-202111",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 5,
        even: true,
        last: true,
      },
    ],
    price: "11599.00",
  },
  {
    productName: "MacBook Air com M2",
    id: "imacairm2",
    posterImg: {
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-digitalmat-gallery-2-202206_GEO_BR?wid=728&hei=666&fmt=png-alpha&.v=1653624579020",
      alt: "Visão superior do MacBook Air mostrando a tela e o Magic Keyboard.",
    },
    images: [
      {
        index: 0,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-digitalmat-gallery-1-202206?wid=728&hei=666&fmt=png-alpha&.v=1652827325377",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1652827325377",
          },
          attrs: "",
          alt: "Imagem de perfil do MacBook Air nas cores prateado, estelar, cinza-espacial e meia-noite.",
          width: "364",
          height: "333",
          imageName: "macbook-air-digitalmat-gallery-1-202206",
          originalImageName: "macbook-air-digitalmat-gallery-1-202206",
          noImage: false,
          deferSrc: false,
        },
        first: true,
        position: 1,
        even: true,
        last: false,
      },
      {
        index: 1,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-digitalmat-gallery-2-202206_GEO_BR?wid=728&hei=666&fmt=png-alpha&.v=1653624579020",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1653624579020",
          },
          attrs: "",
          alt: "Visão superior do MacBook Air mostrando a tela e o Magic Keyboard.",
          width: "364",
          height: "333",
          imageName: "macbook-air-digitalmat-gallery-2-202206_GEO_BR",
          originalImageName: "macbook-air-digitalmat-gallery-2-202206_GEO_BR",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 2,
        even: false,
        last: false,
      },
      {
        index: 2,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-digitalmat-gallery-3-202206?wid=728&hei=666&fmt=png-alpha&.v=1652827325419",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1652827325419",
          },
          attrs: "",
          alt: "Imagem de perfil de dois modelos do MacBook Air abertos, um de costas para o outro, mostrando o design fino.",
          width: "364",
          height: "333",
          imageName: "macbook-air-digitalmat-gallery-3-202206",
          originalImageName: "macbook-air-digitalmat-gallery-3-202206",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 3,
        even: true,
        last: false,
      },
      {
        index: 3,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-digitalmat-gallery-4-202206?wid=728&hei=666&fmt=png-alpha&.v=1652827325434",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1652827325434",
          },
          attrs: "",
          alt: "Imagem de perfil de quatro modelos do MacBook Air mostrando as portas para recarga e expansão.",
          width: "364",
          height: "333",
          imageName: "macbook-air-digitalmat-gallery-4-202206",
          originalImageName: "macbook-air-digitalmat-gallery-4-202206",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 4,
        even: false,
        last: false,
      },
      {
        index: 4,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-digitalmat-gallery-5-202206?wid=728&hei=666&fmt=png-alpha&.v=1652827325475",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1652827325475",
          },
          attrs: "",
          alt: "Visão superior de um MacBook Air fechado.",
          width: "364",
          height: "333",
          imageName: "macbook-air-digitalmat-gallery-5-202206",
          originalImageName: "macbook-air-digitalmat-gallery-5-202206",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 5,
        even: true,
        last: false,
      },
      {
        index: 5,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-digitalmat-gallery-6-202206?wid=728&hei=666&fmt=png-alpha&.v=1652827325432",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1652827325432",
          },
          attrs: "",
          alt: "Visão superior de um MacBook Air aberto na cor meia-noite e de três modelos de MacBook Air fechados nas cores estelar, cinza-espacial e prateado.",
          width: "364",
          height: "333",
          imageName: "macbook-air-digitalmat-gallery-6-202206",
          originalImageName: "macbook-air-digitalmat-gallery-6-202206",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 6,
        even: false,
        last: false,
      },
      {
        index: 6,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-digitalmat-gallery-7-202206?wid=728&hei=666&fmt=png-alpha&.v=1652827325557",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1652827325557",
          },
          attrs: "",
          alt: "Mulher tocando um teclado com uma mão enquanto segura um MacBook Air aberto na outra.",
          width: "364",
          height: "333",
          imageName: "macbook-air-digitalmat-gallery-7-202206",
          originalImageName: "macbook-air-digitalmat-gallery-7-202206",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 7,
        even: true,
        last: true,
      },
    ],
    price: "13999.00",
  },
  {
    productName: "MacBook Pro de 13 pol.",
    id: "imac13",
    price: "15299.00",
    images: [
      {
        index: 0,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-digitalmat-gallery-1-202206?wid=728&hei=666&fmt=png-alpha&.v=1652888111197",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1652888111197",
          },
          attrs: "",
          alt: "Parte frontal de um MacBook Pro de 13 polegadas aberto.",
          width: "364",
          height: "333",
          imageName: "mbp-digitalmat-gallery-1-202206",
          originalImageName: "mbp-digitalmat-gallery-1-202206",
          noImage: false,
          deferSrc: false,
        },
        first: true,
        position: 1,
        even: true,
        last: false,
      },
      {
        index: 1,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-digitalmat-gallery-2-202206_GEO_BR?wid=728&hei=666&fmt=png-alpha&.v=1653527892625",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1653527892625",
          },
          attrs: "",
          alt: "Visão superior do MacBook Pro de 13 polegadas mostrando a tela Retina e o Magic Keyboard.",
          width: "364",
          height: "333",
          imageName: "mbp-digitalmat-gallery-2-202206_GEO_BR",
          originalImageName: "mbp-digitalmat-gallery-2-202206_GEO_BR",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 2,
        even: false,
        last: false,
      },
      {
        index: 2,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-digitalmat-gallery-3-202206?wid=728&hei=666&fmt=png-alpha&.v=1652888111181",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1652888111181",
          },
          attrs: "",
          alt: "Imagem de perfil de dois modelos do MacBook Pro de 13 polegadas mostrando duas portas Thunderbolt e uma entrada para fones de ouvido.",
          width: "364",
          height: "333",
          imageName: "mbp-digitalmat-gallery-3-202206",
          originalImageName: "mbp-digitalmat-gallery-3-202206",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 3,
        even: true,
        last: false,
      },
      {
        index: 3,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-digitalmat-gallery-4-202206?wid=728&hei=666&fmt=png-alpha&.v=1652888111195",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1652888111195",
          },
          attrs: "",
          alt: "Visão superior de dois modelos do MacBook Pro de 13 polegadas nas cores prateado e cinza-espacial.",
          width: "364",
          height: "333",
          imageName: "mbp-digitalmat-gallery-4-202206",
          originalImageName: "mbp-digitalmat-gallery-4-202206",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 4,
        even: false,
        last: true,
      },
    ],
    posterImg: {
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-digitalmat-gallery-1-202206?wid=728&hei=666&fmt=png-alpha&.v=1652888111197",
      alt: "Parte frontal de um MacBook Pro de 13 polegadas aberto.",
    },
  },
  {
    productName: "MacBook Pro de 14 e 16 pol.",
    id: "imac1416",
    price: "23699.00",
    images: [
      {
        index: 0,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-14-digitalmat-gallery-1-202111?wid=728&hei=666&fmt=png-alpha&.v=1635183223000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635183223000",
          },
          attrs: "",
          alt: "Visão frontal da tela Liquid Retina XDR de 14 polegadas. ",
          width: "364",
          height: "333",
          imageName: "mbp-14-digitalmat-gallery-1-202111",
          originalImageName: "mbp-14-digitalmat-gallery-1-202111",
          noImage: false,
          deferSrc: false,
        },
        first: true,
        position: 1,
        even: true,
        last: false,
      },
      {
        index: 1,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-14-digitalmat-gallery-2-202111?wid=728&hei=666&fmt=png-alpha&.v=1635183221000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635183221000",
          },
          attrs: "",
          alt: "Closes da porta MagSafe 3, de duas portas Thunderbolt 4 e de uma entrada para fones de ouvido no lado esquerdo. Slot para cartão SDXC, uma porta Thunderbolt 4 e uma porta HDMI no lado direito.",
          width: "364",
          height: "333",
          imageName: "mbp-14-digitalmat-gallery-2-202111",
          originalImageName: "mbp-14-digitalmat-gallery-2-202111",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 2,
        even: false,
        last: false,
      },
      {
        index: 2,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-14-digitalmat-gallery-3-202111_GEO_BR?wid=728&hei=666&fmt=png-alpha&.v=1636043515000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1636043515000",
          },
          attrs: "",
          alt: "Visão superior do teclado, do trackpad e das grades do alto-falante.",
          width: "364",
          height: "333",
          imageName: "mbp-14-digitalmat-gallery-3-202111_GEO_BR",
          originalImageName: "mbp-14-digitalmat-gallery-3-202111_GEO_BR",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 3,
        even: true,
        last: false,
      },
      {
        index: 3,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-14-digitalmat-gallery-4-202111_GEO_BR?wid=728&hei=666&fmt=png-alpha&.v=1636043541000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1636043541000",
          },
          attrs: "",
          alt: "Close do teclado com sensor Touch ID.",
          width: "364",
          height: "333",
          imageName: "mbp-14-digitalmat-gallery-4-202111_GEO_BR",
          originalImageName: "mbp-14-digitalmat-gallery-4-202111_GEO_BR",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 4,
        even: false,
        last: false,
      },
      {
        index: 4,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-14-digitalmat-gallery-5-202111?wid=728&hei=666&fmt=png-alpha&.v=1635183222000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635183222000",
          },
          attrs: "",
          alt: "Visão da lateral esquerda do MacBook Pro com a tela aberta.",
          width: "364",
          height: "333",
          imageName: "mbp-14-digitalmat-gallery-5-202111",
          originalImageName: "mbp-14-digitalmat-gallery-5-202111",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 5,
        even: true,
        last: true,
      },
    ],
    posterImg: {
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mbp-14-digitalmat-gallery-1-202111?wid=728&hei=666&fmt=png-alpha&.v=1635183223000",
      alt: "Visão frontal da tela Liquid Retina XDR de 14 polegadas.",
    },
  },
  {
    productName: "iMac de 24 polegadas",
    id: "imac24",
    price: "14799.00",
    posterImg: {
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/imac24-digitalmat-gallery-2-202111?wid=728&hei=666&fmt=png-alpha&.v=1635186198000",
      alt: "Visão frontal da tela Retina 4.5K com o Magic Keyboard e o Magic Trackpad.",
    },
    images: [
      {
        index: 0,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/imac24-digitalmat-gallery-1-202111?wid=728&hei=666&fmt=png-alpha&.v=1635186197000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635186197000",
          },
          attrs: "",
          alt: "Visão das sete cores, incluindo prateado, azul, roxo, rosa, laranja, amarelo e verde.",
          width: "364",
          height: "333",
          imageName: "imac24-digitalmat-gallery-1-202111",
          originalImageName: "imac24-digitalmat-gallery-1-202111",
          noImage: false,
          deferSrc: false,
        },
        first: true,
        position: 1,
        even: true,
        last: false,
      },
      {
        index: 1,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/imac24-digitalmat-gallery-2-202111?wid=728&hei=666&fmt=png-alpha&.v=1635186198000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635186198000",
          },
          attrs: "",
          alt: "Visão frontal da tela Retina 4.5K com o Magic Keyboard e o Magic Trackpad.",
          width: "364",
          height: "333",
          imageName: "imac24-digitalmat-gallery-2-202111",
          originalImageName: "imac24-digitalmat-gallery-2-202111",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 2,
        even: false,
        last: false,
      },
      {
        index: 2,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/imac24-digitalmat-gallery-3-202111?wid=728&hei=666&fmt=png-alpha&.v=1635186200000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635186200000",
          },
          attrs: "",
          alt: "Visão da parte de trás, com duas portas Thunderbolt / USB 4, duas portas USB 3 e porta Gigabit Ethernet.",
          width: "364",
          height: "333",
          imageName: "imac24-digitalmat-gallery-3-202111",
          originalImageName: "imac24-digitalmat-gallery-3-202111",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 3,
        even: true,
        last: false,
      },
      {
        index: 3,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/imac24-digitalmat-gallery-4-202111?wid=728&hei=666&fmt=png-alpha&.v=1635186199000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635186199000",
          },
          attrs: "",
          alt: "Visão lateral do design fino de 11,5 mm na base ajustável.",
          width: "364",
          height: "333",
          imageName: "imac24-digitalmat-gallery-4-202111",
          originalImageName: "imac24-digitalmat-gallery-4-202111",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 4,
        even: false,
        last: false,
      },
      {
        index: 4,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/imac24-digitalmat-gallery-5-202111?wid=728&hei=666&fmt=png-alpha&.v=1635186199000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635186199000",
          },
          attrs: "",
          alt: "Visão lateral do cabo em tecido conectado magneticamente na parte de trás e na mesma cor do iMac.",
          width: "364",
          height: "333",
          imageName: "imac24-digitalmat-gallery-5-202111",
          originalImageName: "imac24-digitalmat-gallery-5-202111",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 5,
        even: true,
        last: true,
      },
    ],
  },
  {
    productName: "Mac mini",
    id: "macmini",
    price: "8499.00",
    images: [
      {
        index: 0,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-mini-digitalmat-gallery-1-202111?wid=728&hei=666&fmt=png-alpha&.v=1635186947000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635186947000",
          },
          attrs: "",
          alt: "Visão angulada da parte da frente mostrando o Mac Mini prateado com o logotipo da Apple em cima.",
          width: "364",
          height: "333",
          imageName: "mac-mini-digitalmat-gallery-1-202111",
          originalImageName: "mac-mini-digitalmat-gallery-1-202111",
          noImage: false,
          deferSrc: false,
        },
        first: true,
        position: 1,
        even: true,
        last: false,
      },
      {
        index: 1,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-mini-digitalmat-gallery-2-202111?wid=728&hei=666&fmt=png-alpha&.v=1635186947000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635186947000",
          },
          attrs: "",
          alt: "Visão da parte de trás com duas portas Thunderbolt / USB 4, duas portas USB-A, porta HDMI 2.0, porta Gigabit Ethernet e entrada para fones de ouvido.",
          width: "364",
          height: "333",
          imageName: "mac-mini-digitalmat-gallery-2-202111",
          originalImageName: "mac-mini-digitalmat-gallery-2-202111",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 2,
        even: false,
        last: false,
      },
      {
        index: 2,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-mini-digitalmat-gallery-3-202111?wid=728&hei=666&fmt=png-alpha&.v=1635186948000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635186948000",
          },
          attrs: "",
          alt: "Visão lateral mostrando o design fino de 1,4 polegada.",
          width: "364",
          height: "333",
          imageName: "mac-mini-digitalmat-gallery-3-202111",
          originalImageName: "mac-mini-digitalmat-gallery-3-202111",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 3,
        even: true,
        last: false,
      },
      {
        index: 3,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-mini-digitalmat-gallery-4-202111?wid=728&hei=666&fmt=png-alpha&.v=1635186948000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1635186948000",
          },
          attrs: "",
          alt: "Visão superior em prateado com o logotipo da Apple no centro.",
          width: "364",
          height: "333",
          imageName: "mac-mini-digitalmat-gallery-4-202111",
          originalImageName: "mac-mini-digitalmat-gallery-4-202111",
          noImage: false,
          deferSrc: false,
        },
        first: false,
        position: 4,
        even: false,
        last: true,
      },
    ],
    posterImg: {
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-mini-digitalmat-gallery-1-202111?wid=728&hei=666&fmt=png-alpha&.v=1635186947000",
      alt: "Visão angulada da parte da frente mostrando o Mac Mini prateado com o logotipo da Apple em cima.",
    },
  },
  {
    productName: "Mac Studio",
    id: "macstudio",
    price: "1999.00",
    images: [
      {
        index: 0,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-studio-digitalmat-gallery-1-202203?wid=728&hei=666&fmt=png-alpha&.v=1645207723410",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1645207723410",
          },
          attrs: "",
          alt: "Visão da parte da frente do Mac Studio.",
          width: "364",
          height: "333",
          imageName: "mac-studio-digitalmat-gallery-1-202203",
          originalImageName: "mac-studio-digitalmat-gallery-1-202203",
          noImage: false,
          deferSrc: false,
        },
        position: 1,
        first: true,
        last: false,
        even: true,
      },
      {
        index: 1,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-studio-digitalmat-gallery-2-202203?wid=728&hei=666&fmt=png-alpha&.v=1645207723396",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1645207723396",
          },
          attrs: "",
          alt: "Visão da parte de trás do Mac Studio mostrando quatro portas Thunderbolt 4, porta Ethernet de 10 Gb, entrada de energia, duas portas USB-A, porta HDMI e entrada para fones de ouvido.",
          width: "364",
          height: "333",
          imageName: "mac-studio-digitalmat-gallery-2-202203",
          originalImageName: "mac-studio-digitalmat-gallery-2-202203",
          noImage: false,
          deferSrc: false,
        },
        position: 2,
        first: false,
        last: false,
        even: false,
      },
      {
        index: 2,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-studio-digitalmat-gallery-3-202203?wid=728&hei=666&fmt=png-alpha&.v=1645207723358",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1645207723358",
          },
          attrs: "",
          alt: "Visão superior em prateado com o logotipo da Apple no centro.",
          width: "364",
          height: "333",
          imageName: "mac-studio-digitalmat-gallery-3-202203",
          originalImageName: "mac-studio-digitalmat-gallery-3-202203",
          noImage: false,
          deferSrc: false,
        },
        position: 3,
        first: false,
        last: false,
        even: true,
      },
      {
        index: 3,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-studio-digitalmat-gallery-4-202203?wid=728&hei=666&fmt=jpeg&qlt=90&.v=1645207723416",
            scaleParams1: "wid=364&hei=333&fmt=jpeg&qlt=95&.v=1645207723416",
          },
          attrs: "",
          alt: "Visão da parte inferior do Mac Studio mostrando as saídas de ar.",
          width: "364",
          height: "333",
          imageName: "mac-studio-digitalmat-gallery-4-202203",
          originalImageName: "mac-studio-digitalmat-gallery-4-202203",
          noImage: false,
          deferSrc: false,
        },
        position: 4,
        first: false,
        last: false,
        even: false,
      },
      {
        index: 4,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-studio-digitalmat-gallery-5-202203?wid=728&hei=666&fmt=png-alpha&.v=1646257261656",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1646257261656",
          },
          attrs: "",
          alt: "Mac Studio ao lado de um Studio Display de 27 polegadas para comparar o tamanho.",
          width: "364",
          height: "333",
          imageName: "mac-studio-digitalmat-gallery-5-202203",
          originalImageName: "mac-studio-digitalmat-gallery-5-202203",
          noImage: false,
          deferSrc: false,
        },
        position: 5,
        first: false,
        last: true,
        even: true,
      },
    ],
    posterImg: {
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-studio-digitalmat-gallery-1-202203?wid=728&hei=666&fmt=png-alpha&.v=1645207723410",
      alt: "Visão da parte da frente do Mac Studio.",
    },
  },
  {
    productName: "Mac Pro",
    id: "macpro",
    images: [
      {
        index: 0,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-pro-digitalmat-gallery-1-202111?wid=728&hei=666&fmt=jpeg&qlt=90&.v=1636480313000",
            scaleParams1: "wid=364&hei=333&fmt=jpeg&qlt=95&.v=1636480313000",
          },
          attrs: "",
          alt: "Visão da parte da frente do Mac Pro prateado com o logotipo da Apple no centro.",
          width: "364",
          height: "333",
          imageName: "mac-pro-digitalmat-gallery-1-202111",
          originalImageName: "mac-pro-digitalmat-gallery-1-202111",
          noImage: false,
          deferSrc: false,
        },
        position: 1,
        first: true,
        last: false,
        even: true,
      },
      {
        index: 1,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-pro-digitalmat-gallery-2-202111?wid=728&hei=666&fmt=png-alpha&.v=1636480313000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1636480313000",
          },
          attrs: "",
          alt: "Visão do processador, 12 slots DIMM, dois Módulos MPX, oito slots de expansão, placa de aceleração e módulos de armazenamento SSD.",
          width: "364",
          height: "333",
          imageName: "mac-pro-digitalmat-gallery-2-202111",
          originalImageName: "mac-pro-digitalmat-gallery-2-202111",
          noImage: false,
          deferSrc: false,
        },
        position: 2,
        first: false,
        last: false,
        even: false,
      },
      {
        index: 2,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-pro-digitalmat-gallery-3-202111?wid=728&hei=666&fmt=png-alpha&.v=1636480312000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1636480312000",
          },
          attrs: "",
          alt: "Visão lateral do design ventilado, na posição vertical como se fosse uma torre.",
          width: "364",
          height: "333",
          imageName: "mac-pro-digitalmat-gallery-3-202111",
          originalImageName: "mac-pro-digitalmat-gallery-3-202111",
          noImage: false,
          deferSrc: false,
        },
        position: 3,
        first: false,
        last: false,
        even: true,
      },
      {
        index: 3,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-pro-digitalmat-gallery-4-202111?wid=728&hei=666&fmt=png-alpha&.v=1636480312000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1636480312000",
          },
          attrs: "",
          alt: "Visão superior das duas portas Thunderbolt 3, do botão de liga/desliga e da trava superior.",
          width: "364",
          height: "333",
          imageName: "mac-pro-digitalmat-gallery-4-202111",
          originalImageName: "mac-pro-digitalmat-gallery-4-202111",
          noImage: false,
          deferSrc: false,
        },
        position: 4,
        first: false,
        last: false,
        even: false,
      },
      {
        index: 4,
        value: {
          scaleFactor: "RETINA",
          srcSet: {
            src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-pro-digitalmat-gallery-5-202111?wid=728&hei=666&fmt=png-alpha&.v=1636480311000",
            scaleParams1: "wid=364&hei=333&fmt=png-alpha&.v=1636480311000",
          },
          attrs: "",
          alt: "Visão angulada do design ventilado e resistente da configuração em rack.",
          width: "364",
          height: "333",
          imageName: "mac-pro-digitalmat-gallery-5-202111",
          originalImageName: "mac-pro-digitalmat-gallery-5-202111",
          noImage: false,
          deferSrc: false,
        },
        position: 5,
        first: false,
        last: true,
        even: true,
      },
    ],
    price: "62999.00",
    posterImg: {
      src: "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/mac-pro-digitalmat-gallery-1-202111?wid=728&hei=666&fmt=jpeg&qlt=90&.v=1636480313000",
      alt: "Visão da parte da frente do Mac Pro prateado com o logotipo da Apple no centro.",
    },
  },
];
module.exports = {
  iphones,
  mac,
  products: [...iphones, ...mac],
};
